spring:
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
  messages:
    basename: messages
  web:
    resources:
      static-locations: classpath:/static/